---
- name: Test RHSCL container images on OpenShift 4
  hosts: "{{ hosts | default('localhost') }}"
  vars:
    testing_dir: "/tmp/rhscl_openshift_dir"
    github_repo: "{{ lookup('env', 'GITHUB_REPO')}}"
    ext_test: "{{ lookup('env', 'EXT_TEST') }}"
    xml_file_name: "rhscl-testing-results.xml"
    xml_file: "{{ testing_dir }}/{{ xml_file_name }}"
    xml_testsuite_path: "/testsuite"
    xml_testcase_path: "{{ xml_testsuite_path }}/testcase"
    oc_project_rhscl: "rhscl-ci-testing"
    oc_project_dotnet: "dotnet-ci-testing"
    java_8:
      - java-8-container
    java_11:
      - java-11-container
    java_17:
      - java-17-container
    java: "{{ java_8 + java_11 + java_17 }}"
    dotnet_60:
      - rhel8-dotnet60-container
    dotnet_70:
      - rhel8-dotnet70-container
    dotnet: "{{ dotnet_60 + dotnet_70}}"
  tasks:
    - name: Check temporary directory and create XML unit file
      block:
        - name: Remove directory
          file:
            state: absent
            path: "{{ testing_dir }}"
        - name: Create temporary directory
          file:
            state: directory
            path: "{{ testing_dir }}"

        - name: Copy results template file
          copy:
            src: ./vars/{{ xml_file_name }}
            dest: "{{ xml_file }}"
    - block:
      - name: Check if KUBECONFIG is defined
        command: echo "$KUBECONFIG"
        register: kube
      - name: check if kubeconfig is set
        assert:
          that:
          - kube.stdout != ""
          msg: "KUBECONFIG is not defined"
        changed_when: false
      ignore_errors: no

    - name: Clone and test upstream container repositories
      include_tasks: ./tasks/verify_in_openshift.yml
      loop:
        - rhel7-nodejs-ex-14
        - rhel7-nginx-ex-118
        - rhel7-nginx-ex-120
        - rhel7-postgresql-10-container
        - rhel7-mysql-80-container
        - rhel7-mariadb-103-container
        - rhel7-mariadb-105-container
        - rhel7-s2i-perl-530-container
        - rhel7-s2i-ruby-27-container
        - rhel7-s2i-ruby-30-container
        - rhel7-s2i-python-38-container
        - rhel8-nodejs-ex-14
        - rhel8-nodejs-ex-16
        - rhel8-nodejs-ex-18
        - rhel8-cakephp-ex-73
        - rhel8-cakephp-ex-74
        #- rhel8-cakephp-ex-80 It looks like no prepared for PHP-8.0
        #- rhel8-cakephp-ex-81 It looks like no prepared for PHP-8.0
        - rhel8-httpd-ex
        - rhel8-django-ex-python-36
        - rhel8-django-ex-python-38
        - rhel8-mariadb-105-container
        - rhel8-s2i-perl-530-container
        - rhel8-s2i-perl-526-container
        - rhel8-s2i-python-36-container
        - rhel8-s2i-python-38-container
        - rhel8-s2i-python-39-container
        - rhel8-postgresql-10-container
        - rhel8-postgresql-12-container
        - rhel8-postgresql-13-container
        - rhel8-s2i-ruby-25-container
        - rhel8-s2i-ruby-27-container
        - rhel8-s2i-ruby-30-container
        - rhel8-s2i-ruby-31-container
        - rhel8-mysql-80-container
        - rhel8-nginx-ex-118
        - rhel8-nginx-ex-120
        - rhel9-httpd-ex
        - rhel9-mariadb-105-container
        - rhel9-mysql-80-container
        - rhel9-nginx-ex-120
        - rhel9-nodejs-ex-16
        - rhel9-nodejs-ex-18
        - rhel9-postgresql-13-container
        - rhel9-s2i-perl-532-container
        - rhel9-s2i-python-39-container
        - rhel9-s2i-ruby-30-container
        - rhel9-s2i-ruby-31-container
      when: (github_repo == "") and (ext_test == "")

    - name: Clone and test only one upstream container repository
      include_tasks: ./tasks/verify_in_openshift.yml
      loop:
        - "{{ github_repo }}"
      when: (github_repo is defined) and (github_repo != "") and (ext_test == "")

    - name: Check java container
      include_tasks: ./plugins/verify_java.yml
      loop: "{{ lookup('vars', ext_test) }}"
      when: (ext_test is defined) and (ext_test in
        ["java", "java_8", "java_11", "java_17"])

    - name: Check dotnet containers
      include_tasks: ./tasks/verify_in_openshift.yml
      loop: "{{ lookup('vars', ext_test) }}"
      when: (ext_test is defined) and (ext_test in
        ["dotnet", "dotnet_60", "dotnet_70"])
