---
- name: Test RHSCL container images on OpenShift 4
  hosts: "{{ hosts | default('localhost') }}"
  vars:
    testing_dir: "/tmp/rhscl_openshift_dir"
    github_repo: "{{ lookup('env', 'GITHUB_REPO')}}"
    ext_test: "{{ lookup('env', 'EXT_TEST') }}"
    xml_file_name: "rhscl-testing-results.xml"
    xml_file: "{{ testing_dir }}/{{ xml_file_name }}"
    xml_testsuite_path: "/testsuite"
    xml_testcase_path: "{{ xml_testsuite_path }}/testcase"
    java_8:
      - java-8-container
    java_11:
      - java-11-container
    java: "{{ java_8 + java_11 }}"
    dotnet_21:
      - rhel7-dotnet21-container
      - rhel8-dotnet21-container
    dotnet_31:
      - rhel7-dotnet31-container
      - rhel8-dotnet31-container
    dotnet_50:
      - rhel8-dotnet50-container
    dotnet: "{{ dotnet_21 + dotnet_31 + dotnet_50}}"
  tasks:
    - name: Check temporary directory and create XML unit file
      block:
        - name: Remove directory
          file:
            state: absent
            path: "{{ testing_dir }}"
        - name: Create temporary directory
          file:
            state: directory
            path: "{{ testing_dir }}"

        - name: Copy results template file
          copy:
            src: ./vars/{{ xml_file_name }}
            dest: "{{ xml_file }}"
    - block:
      - name: Check if KUBECONFIG is defined
        command: echo "$KUBECONFIG"
        register: kube
      - name: check if kubeconfig is set
        assert:
          that:
          - kube.stdout != ""
          msg: "KUBECONFIG is not defined"
        changed_when: false
      ignore_errors: no

    - name: Clone and test upstream container repositories
      include_tasks: ./tasks/verify_in_openshift.yml
      loop:
        - nodejs-ex
        - cakephp-ex
        - httpd-ex
        - nginx-ex
        - django-ex
        - rhel7-postgresql-10-container
        - rhel7-mysql-80-container
        - rhel7-mariadb-103-container
        - rhel7-s2i-ruby-25-container
        - rhel7-s2i-python-36-container
        - rhel7-s2i-perl-526-container
        - rhel8-s2i-perl-526-container
        - rhel8-s2i-python-36-container
        #- rhel8-s2i-python-38-container Problem with deploying # error: the image match "python:3.8" for source repository "https://github.com/sclorg/s2i-python-container.git" does not appear to be a source-to-image builder.
        - rhel8-s2i-ruby-25-container
        #- rhel8-s2i-ruby-26-container Problem with deploying # error: the image match "ruby:2.6" for source repository "https://github.com/sclorg/s2i-ruby-container.git" does not appear to be a source-to-image builder.
        - rhel8-mysql-80-container
      when: (github_repo == "") and (ext_test == "")

    - name: Clone and test only one upstream container repository
      include_tasks: ./tasks/verify_in_openshift.yml
      loop:
        - "{{ github_repo }}"
      when: (github_repo is defined) and (github_repo != "") and (ext_test == "")

    - name: Check java container
      include_tasks: ./plugins/verify_java.yml
      loop: "{{ lookup('vars', ext_test) }}"
      when: (ext_test is defined) and (ext_test in
        ["java", "java_8", "java_11"])

    - name: Check dotnet containers
      include_tasks: ./tasks/verify_in_openshift.yml
      loop: "{{ lookup('vars', ext_test) }}"
      when: (ext_test is defined) and (ext_test in
        ["dotnet", "dotnet_21", "dotnet_31", "dotnet_50"])
