- block:
  - name: Import image {{ stuff.registry_redhat_io }} into OpenShift 4 environment
    shell: "oc import-image {{ stuff.tag_name }} --from=registry.redhat.io/{{ stuff.registry_redhat_io }}:latest --insecure=true --confirm"
    register: oc_import

  - debug: var=oc_import
  when: stuff.registry_redhat_io is defined

- block:
  - name: Deploying container {{ item }} into OpenShift 4 environment
    shell: "{{ stuff.deployment }}"
    changed_when: false
    register: deploy_cmd
    ignore_errors: yes

  - debug: var=deploy_cmd

  - name: Check if POD {{ stuff.pod_name }} is running
    script: "./files/check_pod_running.sh {{ stuff.pod_name }}"
    register: cluster_name
    until: cluster_name.rc == 0
    retries: 40
    delay: 30
    ignore_errors: yes
    when: deploy_cmd.rc == 0

  - debug: var=cluster_name

  - name: Expose route with name {{ stuff.pod_name }} for testing
    shell: "oc expose svc/{{ stuff.pod_name }} --name={{ stuff.pod_name }}"
    when: (stuff.add_route is defined) and (deploy_cmd.rc == 0) and (cluster_name.rc == 0)

  - name: Check if POD {{ stuff.pod_name }} exposes route
    shell: "oc get routes --no-headers -o custom-columns=HOST:.spec.host | grep {{ stuff.pod_name }}"
    changed_when: false
    register: route_cmd
    until: route_cmd.rc == 0
    retries: 10
    delay: 20
    when: (deploy_cmd.rc == 0) and (cluster_name.rc == 0)

  - debug: var=route_cmd
  when: file_exists.stat.exists
