- block:
  - name: Check curl command is working
    uri:
      url: "http://{{ route_cmd.stdout }}"
      return_content: yes
      status_code: 200
      body_format: "{{ stuff.curl_output_format | default('json') }}"
    retries: 20
    delay: 10
    register: curl_output
    ignore_errors: yes
    until: ("status" in curl_output) and (curl_output.status == 200)

  - name: Check proper output in json
    debug:
      var: curl_output

  - block:
      - name: Write test case failure elements
        xml:
          path: "{{ xml_file }}"
          xpath: "{{ xml_testcase_path }}"
          pretty_print: yes
          add_children:
            - failure:
                message: "Check curl Test failed"
            - system-err: "{{ curl_output.msg | trim }}"

      - name: Increment testsuite failures attribute
        xml:
          path: "{{ xml_file }}"
          xpath: "{{ xml_testsuite_path }}"
          attribute: failures
          value: "{{ testsuite_attrs.failures|int + 1 }}"
    when: (curl_output["content"] is not defined) or ("{{ stuff.check_curl_output }}" not in curl_output["content"])

  - name: Write test case passed elements
    xml:
      path: "{{ xml_file }}"
      xpath: "{{ xml_testcase_path }}"
      pretty_print: yes
      add_children:
        - system-out: "{{ curl_output.msg | trim }}"
    when: '"{{ stuff.check_curl_output }}" in curl_output["content"]'

  when: (stuff.check_curl_output is defined)

- block:
  - name: Running test in pod by oc exec
    script: "{{ stuff.test_exec_command }} {{ cluster_name.stdout | trim }} '{{ stuff.expected_exec_result }}'"
    ignore_errors: yes
    register: command_out
    retries: 20
    delay: 10
    until: command_out.rc == 0

  - debug: var=command_out

  - block:
      - name: Write test case failure elements
        xml:
          path: "{{ xml_file }}"
          xpath: "{{ xml_testcase_path }}"
          pretty_print: yes
          add_children:
            - failure:
                message: "In Pod Test failed"
            - system-err: "{{ command_out.stderr | trim }}"

      - name: Increment testsuite failures attribute
        xml:
          path: "{{ xml_file }}"
          xpath: "{{ xml_testsuite_path }}"
          attribute: failures
          value: "{{ testsuite_attrs.failures|int + 1 }}"
    when: command_out.rc != 0

  - name: Write test case passed elements
    xml:
      path: "{{ xml_file }}"
      xpath: "{{ xml_testcase_path }}"
      pretty_print: yes
      add_children:
        - system-out: "{{ command_out.stdout | trim }}"
    when: command_out.rc == 0

  when: (stuff.test_exec_command is defined)

