- block:
  - debug: var=stuff
  - debug: var=service_ip

  - name: Check if curl command is working
    script: "./files/check_oc_exec_output.sh 'curl {{ service_ip.stdout | trim }}:8080' '{{ cluster_name.stdout | trim }}' '{{ stuff.check_curl_output }}'"
    retries: 5
    delay: 20
    register: curl_output
    ignore_errors: yes
    until: curl_output.rc == 0
#  - name: Check curl command is working
#    uri:
#      url: "http://{{ route_cmd.stdout }}"
#      return_content: yes
#      status_code: 200
#      body_format: "{{ stuff.curl_output_format | default('json') }}"
#    retries: 19
#    delay: 20
#    register: curl_output
#    ignore_errors: yes
#    until: ("status" in curl_output) and (curl_output.status == 200)

  - name: Check proper output
    debug:
      var: curl_output

  - block:
      - name: Write test case failure elements
        xml:
          path: "{{ xml_file }}"
          xpath: "{{ xml_testcase_path }}"
          pretty_print: yes
          add_children:
            - failure:
                message: "Check curl Test failed"
            - system-err: "{{ curl_output.stdout | trim }}"

      - name: Increment testsuite failures attribute
        xml:
          path: "{{ xml_file }}"
          xpath: "{{ xml_testsuite_path }}"
          attribute: failures
          value: "{{ testsuite_attrs.failures|int + 1 }}"
    when: (curl_output["stdout"] is not defined) or ("{{ stuff.check_curl_output }}" not in curl_output["stdout"])

  - name: Write test case passed elements
    xml:
      path: "{{ xml_file }}"
      xpath: "{{ xml_testcase_path }}"
      pretty_print: yes
      add_children:
        - system-out: "FINE"
    when: '"{{ stuff.check_curl_output }}" in curl_output["stdout"]'

  when: (stuff.check_curl_output is defined)

- block:
  - debug: var=cluster_name

  - name: Running test in pod by oc exec
    script: "{{ stuff.test_exec_command }} {{ cluster_name.stdout | trim }} '{{ stuff.expected_exec_result }}'"
    ignore_errors: yes
    register: command_out
    retries: 5
    delay: 20
    until: command_out.rc == 0

  - debug: var=command_out

  - name: Check oc get pods
    command: oc get pods
    register: oc_get_pods
    changed_when: false

  - debug:
      var: oc_get_pods.stdout_lines

  - block:
      - name: Write test case failure elements
        xml:
          path: "{{ xml_file }}"
          xpath: "{{ xml_testcase_path }}"
          pretty_print: yes
          add_children:
            - failure:
                message: "In Pod Test failed"
            - system-err: "{{ command_out.stderr | trim }}"

      - name: Increment testsuite failures attribute
        xml:
          path: "{{ xml_file }}"
          xpath: "{{ xml_testsuite_path }}"
          attribute: failures
          value: "{{ testsuite_attrs.failures|int + 1 }}"
    when: command_out.rc != 0

  - name: Write test case passed elements
    xml:
      path: "{{ xml_file }}"
      xpath: "{{ xml_testcase_path }}"
      pretty_print: yes
      add_children:
        - system-out: "{{ command_out.stdout | trim }}"
    when: command_out.rc == 0

  when: (stuff.test_exec_command is defined)

