name: OpenShift tests by GitHub Action at Testing Farm

on:
  issue_comment:
    types:
      - created
jobs:
  build:
    # This job only runs for '[test]' pull request comments by owner, member
    name: OpenShift tests by GitHub Action on Testing Farm service
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - context: "RHSCL InterOp NoS2I tests"
            ext_test: "nos2i"
          - context: "RHSCL InterOp S2I tests"
            ext_test: "s2i"
          - context: "Java InterOp Tests"
            ext_test: "java"
          - context: "DotNet InterOp Tests"
            ext_test: "dotnet"

    if: |
      github.event.issue.pull_request
      && contains(github.event.comment.body, '[test]')
      && contains(fromJson('["OWNER", "MEMBER"]'), github.event.comment.author_association)
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          ref: "refs/pull/${{ github.event.issue.number }}/head"

      # https://github.com/sclorg/testing-farm-as-github-action
      - name: Schedule tests on external Testing Farm by Testing-Farm-as-github-action
        id: github_action
        uses: sclorg/testing-farm-as-github-action@v2
        with:
          api_key: ${{ secrets.TF_INTERNAL_API_KEY }}
          git_url: "https://gitlab.cee.redhat.com/platform-eng-core-services/sclorg-tmt-plans"
          git_ref: "master"
          tf_scope: "private"
          tmt_plan_regex: "/ansible-tests"
          pull_request_status_name: ${{ matrix.context }}
          update_pull_request_status: true
          variables: "REPO_URL=${{ github.server_url }}/${{ github.repository }};REPO_NAME=${{ github.repository }};PR_NUMBER=${{ github.event.issue.number }};TEST_NAME=ocp4-tests;EXT_TEST=${{ matrix.ext_test }}"
          compose: "RHEL-8.8.0-Nightly"
